spring.application.name=erp_backend

# Puerto del servidor
server.port=8050

# ----------------------
# PERFIL ACTIVO
# ----------------------
# Cambia a 'dev' para desarrollo local con H2
# Cambia a 'prod' para conectar a Supabase
spring.profiles.active=dev

# ----------------------
# CONFIGURACIÓN GENERAL
# ----------------------
# LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=INFO

# SPRING
spring.jackson.time-zone=America/Santiago
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ----------------------
# BASE DE DATOS (H2)
# ----------------------
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:antuandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# URL: http://localhost:8050/swagger-ui/index.html
# h2: http://localhost:8050/h2-console